/*

 SCORE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\tutas\Desktop\gdk\gbdk\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define teskobgWidth 20
#define teskobgHeight 1
#define teskobgBank 0

unsigned char teskobg[] =
{
  0x23,0x13,0x1F,0x22,0x15,0x0B,0x01,0x01,0x01,0x01,
  0x00,0x12,0x15,0x23,0x24,0x0B,0x01,0x01,0x01,0x01
};

/* End of SCORE.C */
