/*

 TESKO.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : C:\Users\tutas\Desktop\gdk\gbdk\tileset.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define teskobgWidth 4
#define teskobgHeight 5
#define teskobgBank 0

unsigned char teskobg[] =
{
	62,63,64,65
  ,66,67,68,69
  ,70,71,72,73
  ,74,75,76,77
  ,78,79,80,81
};

/* End of TESKO.C */
