/*

 TITLE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\tutas\Desktop\gdk\gbdk\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define titleWidth 20
#define titleHeight 1
#define titleBank 0

unsigned char title[] =
{
  0x20,0x22,0x15,0x23,0x23,0x00,0x23,0x24,0x11,0x22,
  0x24,0x00,0x24,0x1F,0x00,0x20,0x1C,0x11,0x29,0x30
};

/* End of TITLE.C */
